name: falcon-7b-finetuning
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - cudatoolkit=11.8
  - pytorch>=2.0.0
  - pytorch-cuda=11.8
  - numpy>=1.24.0
  - pandas>=2.0.0
  - scikit-learn>=1.3.0
  - jupyter
  - ipykernel
  - pyyaml>=6.0
  - tqdm>=4.66.0
  - git
  - psutil>=5.9.0
  
  # Install remaining packages via pip
  - pip:
    - transformers>=4.35.0
    - datasets>=2.14.0
    - accelerate>=0.24.0
    - peft>=0.6.0
    - trl>=0.7.0
    - bitsandbytes>=0.41.0
    - einops>=0.7.0
    - omegaconf>=2.3.0
    - hydra-core>=1.3.0
    - python-dotenv>=1.0.0
    - mlflow>=2.8.0
    - wandb>=0.16.0
    - tensorboard>=2.15.0
    - pydantic>=2.5.0
    - pytest>=7.4.0
    - pytest-cov>=4.1.0
    - pytest-mock>=3.12.0
    - hypothesis>=6.88.0
    - black>=23.0.0
    - isort>=5.12.0
    - flake8>=6.1.0
    - mypy>=1.7.0
    - pre-commit>=3.5.0
    - sphinx>=7.2.0
    - sphinx-rtd-theme>=1.3.0
    - rich>=13.7.0
    - dvc>=3.30.0
    - "dvc[s3]>=3.30.0"
    - fastapi>=0.104.0
    - uvicorn>=0.24.0
    - requests>=2.31.0
    - cryptography>=41.0.0
    - keyring>=24.3.0 